WebApplication1/Models/Birth.cs
namespace WebApplication1.Models
{
    public class Birth
    {
        public string Name { get; set; }
        public DateTime Date { get; set; }
        public int Years => (int)( DateTime.Now - Date).TotalDays / 365;

        public bool isValid()
        {
            return Name != null && Name != String.Empty;
        }
    }
}

WebApplication1/Models/Calculator.cs
public class Calculator
{
    public Operator? op { get; set; }
    public double? A { get; set; }
    public double? B { get; set; }

    public String Op
    {
        get
        {
            switch (op)
            {
                case Operator.add:
                    return "+";                
                case Operator.sub: 
                    return "-";
                case Operator.mul:
                    return "*";
                case Operator.div:
                    return "÷";
                default:
                    return "";
            }
        }
    }

    public bool IsValid()
    {
        return op != null && A != null && B != null;
    }

    public double Calculate()
    {
        switch (op)
        {
            case Operator.add :
                return (double)(A + B);
            case Operator.sub :
                return (double)(A - B);
            case Operator.mul :
                return (double)(A * B);
            case Operator.div :
                return (double)(A / B);
            default: return double.NaN;
        }
    }
    public enum Operator
    {
        mul, div, add, sub
    }
}

WebApplication1/Models/ErrorViewModel.cs
namespace WebApplication1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplication1/Controllers/BirthController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace WebApplication1.Controllers
{
    public class BirthController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Result([FromForm] Birth model)
        {
            
            if (!model.isValid())
            {
                ViewBag.ErrorMessage = "Imie nie moze byc puste";
                return View("CustomError");
            }
            if((int)(DateTime.Now - model.Date).TotalDays < 0)
            {
                ViewBag.ErrorMessage = "Nie mozesz urodzic sie w przyszlosci!";
                return View("CustomError");
            }
            return View(model);
        }
        public IActionResult Form()
        {
            return View();
        }
    }
}

WebApplication1/Controllers/CalculatorController.cs
using Microsoft.AspNetCore.Mvc;
using static WebApplication1.Controllers.HomeController;

namespace WebApplication1.Controllers
{
    public class CalculatorController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Result([FromForm] Calculator model)
        {
            if (!model.IsValid())
            {
                return View("Error");
            }
            return View(model);
        }
        public enum Operator
        {
            mul, div, add, sub
        }
        public IActionResult Form()
        {
            return View();
        }
    }

}

WebApplication1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult About()
        {
            return View();
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
/*        public IActionResult Calculator(Operator? op, double? a, double? b)
        {
            if(op is null)
            {
                ViewBag.ErrorMessage = "Niepoprawny format operatora";
                return View("CustomError");
            }
            if (a is null || b is null)
            {
                ViewBag.ErrorMessage = "Niepoprawny format liczby";
                return View("CustomError");
            }

            ViewBag.op = op;
            ViewBag.a = a; 
            ViewBag.b = b;
            
                switch(op)
            {

                case Operator.add:
                    ViewBag.result = a+b;
                    ViewBag.op = "+";
                    break;
                case Operator.sub:
                    ViewBag.result = a - b;
                    ViewBag.op = "-";
                    break;
                case Operator.mul:
                    ViewBag.result = a * b;
                    ViewBag.op = "×";
                    break;
                case Operator.div:
                    ViewBag.result = a / b;
                    ViewBag.op = "÷";
                    break;
                default:
                    ViewBag.ErrorMessage = "Niepoprawny znak dzialania";
                    return View("CustomError");
                    
            }
            return View();
        }*/

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        public enum Operator 
        { 
        mul, div, add, sub
        }
    }
}

WebApplication1/Views/Birth/Form.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-6">
            <h2>Data urodzenia</h2>
            <form action="Result" method="POST">
                <div class="mb-3">
                    <label class="form-label" for="Name">Imie</label>
                    <input class="form-control" type="text" name="Name" id="a" />
                </div>
                <div class="mb-3">
                    <label class="form-label" for="Date">Liczba 2</label>
                    <input class="form-control" type="date" name="Date" id="b" />
                </div>
                <div class="mb-3">
                    <button class="btn btn-primary" type="submit">Oblicz</button>
                </div>
            </form>
        </div>
    </div>
</div>

WebApplication1/Views/Birth/Result.cshtml
@{
}
<h3>Masz na imie @Model.Name i masz @Model.Years lat</h3>

WebApplication1/Views/Calculator/Form.cshtml
@{
}

<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-6">
            <h2>Kalkulator</h2>
            <form action="Result" method="POST">
                <div class="mb-3">
                    <label class="form-label" for="x">Liczba 1</label>
                    <input class="form-control" type="number" name="a" step="0.00001" id="a" />
                </div>
                <div class="mb-3">
                    <label class="form-label" for="operator">Operator</label>
                    <select name="op">
                        <option value="add">+</option>
                        <option value="sub">&minus;</option>
                        <option value="mul">&times;</option>
                        <option value="div">&divide;</option>
                    </select>
                </div>
                <div class="mb-3">
                    <label class="form-label" for="y">Liczba 2</label>
                    <input class="form-control" type="number" name="b" step="0.00001" id="b" />
                </div>
                <div class="mb-3">
                    <button class="btn btn-primary" type="submit">Oblicz</button>
                </div>
            </form>
        </div>
    </div>
</div>

WebApplication1/Views/Calculator/Result.cshtml
@{
}

<H3>@Model.A @Model.Op @Model.B = <b class="text-danger">@Model.Calculate()</b></H3>

WebApplication1/Views/Home/About.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>About</title>
</head>
<body>
<h2>Cokolwiek</h2>
</body>
</html>

WebApplication1/Views/Home/Calculator.cshtml
@{
    ViewBag.Title = "Kalkulator";
    Layout = "_Layout";
}

<h1>@ViewBag.Title</h1>
<p>Dzialanie: @ViewBag.a @ViewBag.op @ViewBag.b = @ViewBag.result </p>

WebApplication1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebApplication1/Views/Shared/CustomError.cshtml
@{
    ViewBag.Title = "Error!";
    Layout = "_Layout";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CustomError</title>
</head>
<body>
<h2>
    @ViewBag.ErrorMessage
</h2>
</body>
</html>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication1</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Calculator" asp-action="Form">Calculator</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Birth" asp-action="Form">BirthControl</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - WebApplication1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>